# Generated by Django 3.2.5 on 2022-08-05 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(help_text='Shipment origin.', max_length=255)),
                ('destination', models.CharField(help_text='Shipment destination.', max_length=255)),
                ('weight', models.DecimalField(decimal_places=3, help_text='Shipment weight.', max_digits=7, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PLACED', 'Placed'), ('ON_DELIVERY', 'On_delivery'), ('DELIVERED', 'Delivered')], default='CREATED', max_length=11)),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express')], default='NORMAL', max_length=7)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
